[versions]
junit-jupiter = "5.14.1"
junit-platform-launcher = "1.10.2"
openrewrite-bom = "8.66.1"
assertj-core = "3.27.6"

[libraries]
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
openrewrite-bom = { module = "org.openrewrite:rewrite-bom", version.ref = "openrewrite-bom" }
openrewrite-java = { module = "org.openrewrite:rewrite-java" }
openrewrite-gradle = { module = "org.openrewrite:rewrite-gradle" }
openrewrite-java21 = { module = "org.openrewrite:rewrite-java-21" }
openrewrite-test = { module = "org.openrewrite:rewrite-test" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
